config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "emails#index"
  resources :tasks, except: [:show]
  resources :emails
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/email.rb
class Email < ApplicationRecord
  def self.counting
    return Email.all.where(read: false).count
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :authenticate_user!

  def index
    @email = Email.all.order('created_at DESC')
    @readed = Email.counting
  end

  def show
    @email = Email.find(params[:id])
    
    respond_to do |format|
      format.html{
        redirect_to email_path(params[:id])
      }
      format.js{ }
    end
  end

  def create
    @emails = Email.all
    @email = create_email(mail_params)
    @readed = Email.counting
    respond_to do |format|
      format.html{
        redirect_to root_path
      }
      format.js{ }
    end
    # flash[:notice] = "You received a new email"
  end

  def edit
    @email = Email.find(params[:id])
  end

  def update
    @email = Email.find(params[:id])

    if params[:read] == 'true'  
      params[:read] = false
    else
      params[:read] = true
    end
    @email.update(read: params[:read])

    respond_to do |format|
      format.html{
        redirect_to root_path
      }
      format.js{}
    end

    
  end

  def destroy
    @emails = Email.all
    @email = Email.find(params[:id])
    @email.destroy

    respond_to do |format|
      format.html{
        redirect_to root_path
      }
      format.js{ }
    end
    # flash[:error] = "The email has been deleted"
  end

  private

  def create_email(mail_params)
      new_email = Email.create(objet: Faker::Lorem.sentences[0], body: Faker::Lorem.paragraph, email: Faker::Internet.email, read: false)
  end

  def mail_params
    params.permit(:id, :objet, :body, :email, :read)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.all
    @categories = Category.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @categories = Category.all
  end

  def create
    @task = Task.new(task_params)
    @category = Category.find(category_params)
    @task.category = @category
    if @task.save
      respond_to do |format|
        format.html{
          redirect_to root_path
          flash[:notice] = "Task created"
        }
        format.js{ }
      end
    else
      redirect_to root_path
      flash[:notice] = "Please try again"
    end

  end

  def edit
    @task = Task.find(params[:id])
    @categories = Category.all

  end

  def update
    @task = Task.find(params[:id])

    if task_params[:status] == nil
      @task.status = false
    end
    @task.update(task_params)
    respond_to do |format|
      format.html{
        redirect_to tasks_path  
      }
      format.js{}
    end
    flash[:notice] = "Task edited"
  end

  def index
    @tasks = Task.all
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html{
        redirect_to root_path
        flash[:notice] = "Task deleted"
      }
      format.js{}
    end

  end


  private

  def task_params
    params.permit(:id, :title, :deadline, :description, :status)
  end

  def category_params
    params.require(:Category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1 class="text-center mb-4">Welcome to my todolist app</h1>

<div class="container">
  <ul>
  <!-- Default unchecked -->

  <% @categories.each do  |category|%>
  <li><%= category.title  %></li>
  <div class="card">
    <ul class="cat-<%= category.id %>">
      <% category.tasks.each do |task|  %>
      <span class="span">
        <li id="task-<%= task.id %>" class="task">
        <div class="custom-control custom-checkbox">
          <%= check_box_tag :status, true, task.status , data: { remote: true, url: task_path(task.id), params: { title: task.title, deadline: task.deadline}.to_param, method: "put", class: "custom-control-input" }%>
        </div>

          <%= task.title  %>
          <% unless task.deadline.nil? %>
            , to read: <%= task.deadline.strftime('%D')  %>
          <% end %>
          <%= link_to "x", task_path(task.id), method: :delete, class: "far fa-trash-alt delete-btn", remote: true %>
          <%= task.status %>
        </span>
      </li>
      <% end %>
    </ul>
  </div>
  <% end %>
  </ul>
</div>

<div class="container">
  <div class="row">
    <% @tasks.each do |task|  %>
      <div class="card col-3">
        <% unless task.image.nil? %>
          <%= image_tag task.image, class: "rounded-circle" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div>
    <div class="alert alert-warning alert-dismissible fade show m-4" role="alert">
    <p class="alert p-0"><%= msg %></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span span aria-hidden="true">&times;</span>
    </button>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <%= link_to "JJM Email", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <% unless user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "New task", new_task_path, class: "nav-link" %>
      </li>
      
    </ul>
        <img class="rounded-circle" height="50px" width="50px" src="http://digitalspyuk.cdnds.net/17/25/320x320/square-1498216547-avatar-neytiri.jpg">
  </div>
</nav>

app/views/layouts/_task_form.html.erb
<div class="container">

  <div class="row ml-3">
      <div class="offset-md-3 col-md-6 offset-md-3">
          <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form", remote: true)  do %>
              <div class="form-group">
                  <%= label_tag "Task", nil, class: "form-label" %>
                  <%= text_field_tag :title, nil, class: "form-control", placeholder: "Buy burgers" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Deadline", nil, class: "form-label" %>
                  <%= date_field_tag :deadline, nil, class: "form-control" %>

              </div>
              <div class="form-group">
                  <%= label_tag "Category", nil, class: "form-label" %>
                  <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control"  %>
              </div>

              <div class="text-center">
                  <%= submit_tag("Create task", class: "btn btn-start-order") %>
              </div>
          <%end%>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- CSS only -->

  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flash'  %>
    
    <%= yield %>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_new_task.html.erb
<li><%= task.title %> ,to read: <%= task.deadline  %></li>

app/views/tasks/_task_list.html.erb
<ul>
  <% @tasks.each do |task|  %>
    <li>
      <%= task.title %>,
      "Deadline : " <%=  task.deadline.strftime("%D")  %>
       <%= link_to "Edit this task", edit_task_path(task) %>
    </li>
  <% end %>
</ul>

app/views/tasks/create.js.erb
document.querySelector('.cat-<%= @category.id %>').insertAdjacentHTML(
  "beforeend", 
  "<%= j render 'new_task', task: @task %>"
  )

app/views/tasks/destroy.js.erb
document.getElementById("task-<%= @task.id %>").remove()

app/views/tasks/edit.html.erb
<h4>Edit your task</h4>
<%= form_tag(task_path, method: "put", , remote: true) do %>
  <div class="form-group">
      <%= label_tag("Your task:") %>
      <%= text_field_tag(:title, @task.title) %>
  </div>

  <div class="form-group">
    <%= label_tag("When is it due for ?") %>
    <%= date_field_tag(:deadline, @task.deadline)  %>
  </div>
    <%= submit_tag("Edit task", class: "btn btn-info") %>
<% end %>
<%= link_to "Delete this task", task_path(@task), method: :delete, class: "btn btn-danger" %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>

  <%= render 'task_list'  %>

<% end %>

<%= link_to "Create a new task", new_task_path, class: "btn btn-info"  %>

app/views/tasks/new.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/task_form'  %>
<% end %>

app/views/tasks/update.js.erb
document.addEventListener("DOMContentLoaded", function() { 
  
  console.log("Eo")
  
})


text = document.getElementsByClassName('task')
span = document.getElementsByClassName('span')

box = document.querySelectorAll('input')//a partir de4
j = 4
for(i = 0; i < box.length; i++){
  function change_on_click(){
    box[j].addEventListener('click', function(){
      span[i].classList.toggle('checked')
      console.log("eoooooo")
    })
    j++
  }
}